<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Atithih | Channel Manager | Hotel Distribution | Central Reservation System</title>
<meta name="keywords" content="" />
<meta name="description" content="">
<meta name="author" content="">

<!-- Mobile view -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Favicon -->
<link rel="shortcut icon" href="images/Fav-icon.ico">
<link rel="stylesheet" type="text/css" href="js/bootstrap/bootstrap.min.css">

<!-- Google fonts  -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Yesteryear" rel="stylesheet"> 

<!-- Template's stylesheets -->
<link rel="stylesheet" href="js/megamenu/stylesheets/screen.css">
<link rel="stylesheet" href="css/theme-default.css" type="text/css">
<link rel="stylesheet" href="js/loaders/stylesheets/screen.css">
<link rel="stylesheet" href="css/corporate.css" type="text/css">
<link rel="stylesheet" href="css/shortcodes.css" type="text/css">
<link rel="stylesheet" href="fonts/font-awesome/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" type="text/css" href="fonts/Simple-Line-Icons-Webfont/simple-line-icons.css" media="screen" />
<link rel="stylesheet" href="fonts/et-line-font/et-line-font.css">
<link rel="stylesheet" type="text/css" href="js/smart-forms/smart-forms.css">
<link rel="stylesheet" href="css/model.css" type="text/css">


<!-- Template's stylesheets END -->

<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Style Customizer's stylesheets -->

<link rel="stylesheet/less" type="text/css" href="less/skin.less">
<!-- Style Customizer's stylesheets END -->

<!-- Skin stylesheet -->

</head>
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5cbadc4ed6e05b735b437850/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<body>
<div class="wrapper-boxed">
<div class="site-wrapper">

<!-- include header.php -->     
	<?php include('header.php'); ?>
	<!-- Closoing Header.php-->

<!-- include header.php -->   
  
    <div class="clearfix"></div>
    
    <div class="header-inner-tmargin">
        <section class="section-side-image clearfix">
      <div class="container-fluid">
        <div class="row">       
          <div class="col-md-12 col-sm-12 col-xs-12 clearfix nopadding">
           <div style="max-height: 145px; background-color: #19334d; margin-bottom: 0px;" class="header-inner"> 
            <div class="overlay">       
            </div>       
            </div>
          </div>        
        </div>
      </div>
    </section>
    <div class=" clearfix"></div>
    <!--end section-->
    </div>
    <div class="clearfix"></div>
    <!--end header inner-->

		<section class="sec-padding">
		<div class="tab-content-style-6">
   
			<center><h1><b>Terms & Conditions<b></h1></center><br>
			   <ol>
               <p> Please read the following terms and conditions carefully as it sets out the terms of a legally binding agreement between you (the reader) and Atithih (Product of Sunglowsys Technologies Pvt  Ltd.).</p>
				
				<p>In terms of Information Technology Act, 2000, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of Atithih.</p>
				<br>
				<p><b><h5> Privacy Policy and Registration:</b></h5></p>
				<p>All information received by us from your registration on Atithih or other digital products of Sunglowsys Technologies Pvt Ltd. will be used in accordance with our Privacy Policy. Kindly read the below mentioned details.</p>
				<p>On registration, we expect you to provide Atithih with an accurate and complete information of the compulsory fields. We also expect you to keep the information secure, specifically access passwords and payment information. Kindly update the information periodically to keep your account relevant. Atithih will rely on any information you provide to us.</p>
				<p>Each registration is for a single Hotel only. On registration, you will choose a user name and password ("ID"). You are not allowed to share your ID or give access to your account to anyone else. 
					On knowledge, Atithih may cancel or suspend your access to Atithih premium services if it comes across you sharing your personal access without further obligation to you.</p>
				
				<br>
				<p><b><h5> Subscription Period, Renewal and Cancellation:</b></h5></p>
				<br>
				<p><b><h5> Renewals:</b></h5></p>
				<p>If you chose to pay yearly/Monthly, your subscription will continue until you tell us that you no longer wish to receive it, in which case you will stop paying the yearly fees. We will notify you at least 7 days in advance of any changes to the price in your subscription that will apply upon next monthly/ yearly renewal.</p>
				<br>
				<p><b><h5> Cancellation Policy:</b></h5></p>
				<p>For Digital subscriptions by placing your order you agree that we may start your subscription immediately upon our accepting your order. This means that you are not entitled to a refund if you change your mind after we have provided you with access to your subscription.</p>
				<p>Except as set out in the previous section, you do not have any right to cancel your subscription or any part of it until the end of your then current subscription period.<br>Although you may notify us of your intention to cancel at any time, such notice will only take effect at the end of your then current subscription period, and you will not receive a refund.</p>
				<p>Please visit the <b>"How to cancel"</b> section below for details of how to cancel your subscription.</p>
				<p>Unless you notify us before the end of your chosen subscription period that you no longer wish to receive it, your subscription will renew for another period as applicable. We will charge the subscription using the same card or other payment method that you previously used.</p>
				<br>
				<p><b><h5> Types of subscription:</b></h5></p>
				<p>Services may differ from country to country and the device from which you subscribe. Subscriptions packages and price may also vary in time.</p>
				<br>
				<p><b><h5> Pricing errors:</b></h5></p>
				<p>If we incorrectly state a price to you whether online or otherwise, we are not obliged to provide you with a subscription at that price, even if we have mistakenly accepted your offer to buy a subscription at that price, and we reserve the right to subsequently notify you of any pricing error. If we do this, you may cancel the subscription without any obligation to us and we will refund you any money you have paid us in full, or you may pay the correct price. If you refuse to exercise either of these choices then we may cancel your subscription and will refund you any money you have paid us in full. We will always act in good faith in determining whether a genuine pricing error has occurred.</p>
				<br>
				<p><b><h5> Other costs:</b></h5></p>
				<p>In addition to any subscription fees you pay, you are responsible for paying any internet connection or other telecommunications charges that you may incur by accessing the premium services or using the services available on it. For example, if you use any of our mobile services then your network operator may charge you for data or messaging services.</p>
				<br>
				<p><b><h5>Payment details:</b></h5></p>
				<p>When you purchase a subscription, you must provide us with complete and accurate payment information. By submitting payment details you promise that you are entitled to purchase a subscription using those payment details. If we do not receive payment authorization or any authorization is subsequently cancelled, we may immediately terminate or suspend your access to your subscription. In suspicious circumstances we may contact the issuing bank/payment provider and/or law enforcement authorities or other appropriate third parties. If you are entitled to a refund under these terms and conditions we will credit that refund to the card or other payment method you used to submit payment, unless it has expired in which case we will contact you.</p>
				<br>
				<p><b><h5>Responsibilities:</b></h5></p>
				<p>We expect you to follow all instructions set out in the Atithih Guide <br>We will not be responsible if we fail to obtain access to any third party portal or website that is required in order to provide the Service. However, we will make every effort to re-instate the connection.</p>
				<p>It is your responsibility to carefully manage your bookings and inventory. We shall not be responsible for over bookings.<br>We will not be responsible against all claims made by third parties that arise from your failure to perform your obligations under this Agreement.</p>
				<br>
				<p><b><h5>Promotion:</b></h5></p>
				<p>We can represent you as one of our clients in our promotional media and literature and disclose to current and prospective clients and investors that you are a client and user of our products and services.</p>
				<br>
				<p><b><h5>General:</b></h5></p>
				<p>You may not license or transfer any of your rights under these terms and conditions. We may transfer any of our rights or obligations under these terms and conditions to any individual, organization or entity but if we do so we will ensure that any company/individual/entity to whom we transfer our rights or obligations will continue to honour your rights under them. Any resultant changes to the terms and conditions will be intimated to you via email and updated on this website.<br>If any provision of these terms and conditions is found to be invalid by any court having competent jurisdiction, the invalidity of that provision will not affect the validity of the remaining provisions of these terms and conditions, which will remain in full force and effect.<br>Failure by either party to exercise any right or remedy under these terms and conditions does not constitute a waiver of that right or remedy. Headings in these terms and conditions are for convenience only and will have no legal meaning or effect.<br>These terms and conditions constitute the entire agreement between you and Atithih for your use of the Atithih website.</p>
				
				<br>
				<p><b>By using the Service, you confirm your acceptance of the terms of this Agreement, as amended from time to time.</b></p>
				</ol>
				</div>
  </section>
  <!--end item -->
  <div class="clearfix"></div>



 <!-- include footer.php -->     
			<?php include('Footer.php'); ?>
		<!-- Closoing footer-.php-->
	</div>
		<!--end site wrapper--> 
</div>
		<!--end wrapper boxed--> 

		<!-- include footer-link.php -->     
		<?php include('Footer-script.php'); ?>
		<!-- Closoing footer-link.php-->
		<div class="container">
  <div class="row text-center">
         <!-- <button data-toggle="modal" data-target="#modal-switch" class="btn btn-default">Open Modal Popup</button>-->
          <div id="modal-switch" tabindex="-1" role="dialog" aria-labelledby="modal-switch-label" class="modal fade in">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header" style = "background-color:#19334d">
                  <button type="button" data-dismiss="modal" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                    <div id="modal-switch-label" class="modal-title" style = "color:#fff" "font-size: 10px">Schedule Demo</div>
                </div>
                <div class="modal-body">
        
  <form method="post" action="thankyou.php"id="smart-form" class="form-container">
	<input type="text" name="Sendername" id="sendername" class="gui-input" placeholder="Name" required="" style="height: 31px;">

	<input type="email" name="emailaddress" id="emailaddress" class="gui-input" placeholder="Email Address" style="height: 31px;">
	
	<input type="text" name="propertyname" id="propertyname" class="gui-input" placeholder="Property Name" style="height: 31px;">

	<input type="text" name="propertyname" id="propertyname" class="gui-input" placeholder="Property Address" style="height: 31px;">
				
	<input type="pin" pattern="[123456789][0-9]{5}"  name="Pin" id="pin" class="gui-input" placeholder="Pin Code" required"" style="height: 31px;">

	<input type="tel" pattern="[6789][0-9]{9}"  name="telephone" id="telephone" class="gui-input" placeholder="Mob. Number..." required="" style="height: 31px;">
	
	<input type="text" name="product" id="product" class="gui-input" placeholder="Product Looking for..."  style="height: 31px;">
	
	<textarea type="text" class="gui-textarea" id="sendermessage" name="sendermessage" placeholder="Message"></textarea>
                                

    <button type="submit" class="btn">Submit</button>
	<p><br>Please Submit the form to get a call back from our expert</p>
  </form>
</div>
                </div>
              </div>
            </div>
          </div>

  </div>
  </div>

<div class="clearfix"></div>
<script>
function openForm() {
  document.getElementById("myForm").style.display = "block";
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}
</script>
</body>
</html>
